### ISSUE TITLE
Structure et organisation code

### ISSUE THREAD

**Issue by nhannafi** [MdusaCorp/MedusaWebsite#4]
- Mise en place de gitflow
- Organisation globale du code
- Choix de techno

**Comment by Blackolf** [comment]
cette tâche m'intéresse , 
mais c'est possinle d'avoir plus de détail ?
sur 
---
Mise en place de gitflow
Organisation globale du code
Choix de techno

**Comment by BuyukCem** [comment]
Bonjour, 
Nous avons déjà mis en place le gitflow, les techno ont été choisi en vocal discord.
