### ISSUE TITLE
Develop Home page 

### ISSUE THREAD

**Issue by nhannafi** [MdusaCorp/MedusaWebsite#7]
Home page consiste à afficher la présentation du label + navbar

Règles d’affichage :

- une navbar contenant (Home, Présentation Label, Artistes, Récompense reçu, forum, contact)

Critères d’acceptances :

- Etant donné que je suis sur le site quand je clique sur une des sections de la navbar alors je suis redirigé vers la section correspondante

**Comment by BuyukCem** [comment]
Salut @rdaoud  
peux tu regarder car y'a pas les images dans le html.
Merci
